package postgres

import (
	"context"
	"database/sql"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/heguangV/charging-station-platform/backend/internal/order"
	"github.com/heguangV/charging-station-platform/backend/internal/review"
)

// completeOrderForReview drives an order through the full lifecycle to
// COMPLETED and settled (UC-U-12 precondition).
func completeOrderForReview(t *testing.T, db *sql.DB, ctx context.Context, store *OrderStore, suffix string, userID, chargerA int64) order.Order {
	t.Helper()
	created, err := store.CreateOrder(ctx, order.CreateOrderCommand{
		UserID: userID, ChargerID: chargerA, IdempotencyKey: "rv-create-" + suffix, RequestHash: "h", TraceID: "t",
	})
	if err != nil {
		t.Fatalf("CreateOrder() error = %v", err)
	}
	if _, err := store.StartCharging(ctx, order.TransitionCommand{
		UserID: userID, OrderNo: created.OrderNo, IdempotencyKey: "rv-start-" + suffix, RequestHash: "h", TraceID: "t"}); err != nil {
		t.Fatalf("StartCharging() error = %v", err)
	}
	if _, err := store.ConfirmStart(ctx, order.ConfirmStartCommand{
		OrderNo: created.OrderNo, ChargerID: chargerA, OccurredAt: time.Now().UTC()}); err != nil {
		t.Fatalf("ConfirmStart() error = %v", err)
	}
	if _, err := store.StopCharging(ctx, order.TransitionCommand{
		UserID: userID, OrderNo: created.OrderNo, IdempotencyKey: "rv-stop-" + suffix, RequestHash: "h", TraceID: "t"}); err != nil {
		t.Fatalf("StopCharging() error = %v", err)
	}
	if _, err := store.ConfirmStop(ctx, order.ConfirmStopCommand{
		OrderNo: created.OrderNo, ChargerID: chargerA, EnergyWh: 1000, OccurredAt: time.Now().UTC()}); err != nil {
		t.Fatalf("ConfirmStop() error = %v", err)
	}
	if _, err := store.SettleOrder(ctx, order.SettleCommand{
		TransitionCommand: order.TransitionCommand{
			UserID: userID, OrderNo: created.OrderNo, IdempotencyKey: "rv-settle-" + suffix, RequestHash: "h", TraceID: "t"}}); err != nil {
		t.Fatalf("SettleOrder() error = %v", err)
	}
	return created
}

func errorsIsReview(err error, target error) bool {
	return errors.Is(err, target)
}

// applyReviewProposalDDL creates the A-05 tables from migration proposal
// 0009. It is needed only while the proposal awaits B-02 registration; once
// 0009 is a real migration the runner applies it and this becomes a no-op.
func applyReviewProposalDDL(t *testing.T, db *sql.DB, ctx context.Context) {
	t.Helper()
	const ddl = `ALTER TABLE user_accounts ADD COLUMN IF NOT EXISTS avatar_url TEXT NOT NULL DEFAULT '';
ALTER TABLE user_accounts ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
CREATE TABLE IF NOT EXISTS order_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no TEXT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES user_accounts (id),
    station_id BIGINT NOT NULL REFERENCES stations (id),
    stars INT NOT NULL CHECK (stars BETWEEN 1 AND 5),
    comment TEXT NOT NULL CHECK (length(comment) BETWEEN 1 AND 500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_order_reviews_station_created
    ON order_reviews (station_id, created_at DESC);
CREATE TABLE IF NOT EXISTS order_appeals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no TEXT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES user_accounts (id),
    reason TEXT NOT NULL CHECK (length(reason) BETWEEN 1 AND 500),
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED')),
    decided_by BIGINT REFERENCES admin_accounts (id),
    decided_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_order_appeals_status_created
    ON order_appeals (status, created_at DESC);`
	for _, statement := range strings.Split(ddl, ";") {
		if strings.TrimSpace(statement) == "" {
			continue
		}
		if _, err := db.ExecContext(ctx, statement); err != nil {
			t.Fatalf("apply review DDL: %v", err)
		}
	}
}

func TestReviewLifecycleAndWall(t *testing.T) {
	db, ctx := integrationDB(t)
	applyReviewProposalDDL(t, db, ctx)
	reviewStore, err := NewReviewStore(db)
	if err != nil {
		t.Fatalf("NewReviewStore() error = %v", err)
	}
	orderStore2, err := NewOrderStore(db)
	if err != nil {
		t.Fatalf("NewOrderStore() error = %v", err)
	}
	suffix := uniqueSuffix(t)
	userA, userB, stationA, _, chargerA := orderFlowFixture(t, db, ctx, suffix)

	// Give the review author a display name so the wall shows it.
	if _, err := db.ExecContext(ctx, `UPDATE user_accounts SET display_name = '用户0606' WHERE id = $1`, userA); err != nil {
		t.Fatalf("set display name: %v", err)
	}

	created := completeOrderForReview(t, db, ctx, orderStore2, suffix, userA, chargerA)

	// Cross-user review is indistinguishable from a missing order.
	if _, err := reviewStore.CreateReview(ctx, userB, created.OrderNo, 5, "很好"); !errorsIsReview(err, review.ErrNotOrderOwner) {
		t.Fatalf("cross-user review error = %v, want ErrNotOrderOwner", err)
	}

	// Identical replay returns the first result; different content conflicts.
	first, err := reviewStore.CreateReview(ctx, userA, created.OrderNo, 5, "充电很快")
	if err != nil {
		t.Fatalf("CreateReview() error = %v", err)
	}
	replay, err := reviewStore.CreateReview(ctx, userA, created.OrderNo, 5, "充电很快")
	if err != nil || replay.Comment != first.Comment {
		t.Fatalf("replay = %#v, %v", replay, err)
	}
	if _, err := reviewStore.CreateReview(ctx, userA, created.OrderNo, 3, "一般"); !errorsIsReview(err, review.ErrReviewConflict) {
		t.Fatalf("different content error = %v, want ErrReviewConflict", err)
	}

	// The wall shows the review with the masked author.
	// The shared database accumulates rows from earlier runs; assert on the
	// newest entry (the wall is ordered newest first) rather than counts.
	wall, err := reviewStore.ListWall(ctx, review.WallFilter{StationID: stationA, Page: 1, PageSize: 20})
	if err != nil || len(wall.Items) == 0 {
		t.Fatalf("wall = %#v, %v", wall, err)
	}
	if wall.Items[0].Author != "用户0606" || wall.Items[0].Comment != "充电很快" {
		t.Fatalf("newest wall entry = %#v", wall.Items[0])
	}

	// The first appeal succeeds (review and appeal are independent); a
	// second appeal on the same order conflicts.
	if _, err := reviewStore.CreateAppeal(ctx, userA, created.OrderNo, "计量有误"); err != nil {
		t.Fatalf("first appeal error = %v", err)
	}
	if _, err := reviewStore.CreateAppeal(ctx, userA, created.OrderNo, "不同原因"); !errorsIsReview(err, review.ErrAppealConflict) {
		t.Fatalf("second appeal error = %v, want ErrAppealConflict", err)
	}
}

func TestAppealApprovalRefundsWallet(t *testing.T) {
	db, ctx := integrationDB(t)
	applyReviewProposalDDL(t, db, ctx)
	reviewStore, err := NewReviewStore(db)
	if err != nil {
		t.Fatalf("NewReviewStore() error = %v", err)
	}
	orderStore2, err := NewOrderStore(db)
	if err != nil {
		t.Fatalf("NewOrderStore() error = %v", err)
	}
	walletStore, err := NewWalletStore(db)
	if err != nil {
		t.Fatalf("NewWalletStore() error = %v", err)
	}
	suffix := uniqueSuffix(t)
	userA, _, _, _, chargerA := orderFlowFixture(t, db, ctx, suffix)

	created := completeOrderForReview(t, db, ctx, orderStore2, suffix, userA, chargerA)
	settled, err := walletStore.Wallet(ctx, userA)
	if err != nil {
		t.Fatalf("wallet: %v", err)
	}

	appeal, err := reviewStore.CreateAppeal(ctx, userA, created.OrderNo, "计量有误，申请复核")
	if err != nil {
		t.Fatalf("CreateAppeal() error = %v", err)
	}

	// Admin approval: appeal APPROVED, order CANCELLED, wallet refunded.
	if approved, err := reviewStore.ApproveAppeal(ctx, appeal.ID, 9); err != nil || !approved {
		t.Fatalf("ApproveAppeal() = %v, %v", approved, err)
	}

	var orderStatus string
	if err := db.QueryRowContext(ctx, `SELECT status FROM charging_orders WHERE order_no = $1`, created.OrderNo).Scan(&orderStatus); err != nil {
		t.Fatalf("order status: %v", err)
	}
	if orderStatus != "CANCELLED" {
		t.Fatalf("order status = %s, want CANCELLED", orderStatus)
	}
	after, err := walletStore.Wallet(ctx, userA)
	if err != nil {
		t.Fatalf("wallet after refund: %v", err)
	}
	if after.BalanceCent != settled.BalanceCent+120 {
		t.Fatalf("balance = %d, want %d (+120 refund)", after.BalanceCent, settled.BalanceCent)
	}

	// Duplicate approval is a no-op.
	if approved, err := reviewStore.ApproveAppeal(ctx, appeal.ID, 9); err != nil || approved {
		t.Fatalf("duplicate approve = %v, %v; want false", approved, err)
	}

	// The queue reports the approved appeal (shared DB: assert by ID).
	queue, err := reviewStore.ListAppeals(ctx, review.AppealFilter{Status: review.AppealApproved, Page: 1, PageSize: 100})
	if err != nil {
		t.Fatalf("queue error = %v", err)
	}
	found := false
	for _, item := range queue.Items {
		if item.ID == appeal.ID && item.Status == review.AppealApproved {
			found = true
		}
	}
	if !found {
		t.Fatalf("approved appeal %d not in queue: %#v", appeal.ID, queue.Items)
	}
}
