package postgres

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func readP0Migration(t *testing.T) string {
	t.Helper()
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("resolve test filename")
	}
	migrationPath := filepath.Join(filepath.Dir(filename), "../../../migrations/0001_init.sql")
	contents, err := os.ReadFile(migrationPath)
	if err != nil {
		t.Fatalf("read migration: %v", err)
	}
	return strings.ToLower(string(contents))
}

func tableBlocks(schema string) map[string]string {
	blocks := make(map[string]string)
	parts := strings.Split(schema, "create table if not exists ")
	for _, part := range parts[1:] {
		name := part
		if idx := strings.IndexAny(name, " \t\n("); idx >= 0 {
			name = name[:idx]
		}
		blocks[name] = part
	}
	return blocks
}

// readMigration returns one numbered migration, lower-cased like the P0 helper.
func readMigration(t *testing.T, name string) string {
	t.Helper()
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("resolve test filename")
	}
	contents, err := os.ReadFile(filepath.Join(filepath.Dir(filename), "../../../migrations/", name))
	if err != nil {
		t.Fatalf("read migration %s: %v", name, err)
	}
	return strings.ToLower(string(contents))
}

// The BE-I-02 review: the record that keeps one device verdict from being applied twice was an
// idempotency record with a 24-hour window, and an order in STOPPING is still meaningful a day
// later. The structure is therefore the invariant: a command outcome is a permanent fact, so the
// table is keyed by the command id, constrained to the frozen enum, and has no expiry column at all.
func TestChargerCommandOutcomeTableIsDurable(t *testing.T) {
	schema := readMigration(t, "0007_charger_command_outcomes.sql")

	block, ok := tableBlocks(schema)["charger_command_outcomes"]
	if !ok {
		t.Fatal("0007 must define charger_command_outcomes")
	}
	for _, needle := range []string{
		// One command, one verdict: the primary key is the command id itself.
		"command_id text primary key",
		// The database refuses a value the platform must not act on.
		"result text not null check (result in ('completed', 'failed'))",
		"action text not null check (action in ('restart', 'start_charging', 'stop_charging'))",
		"applied boolean not null",
	} {
		if !strings.Contains(block, needle) {
			t.Errorf("charger_command_outcomes must declare %q", needle)
		}
	}
	// Durability is the point: no expiry, no TTL, nothing that would let a duplicate be applied
	// again once a window has passed.
	for _, forbidden := range []string{"expires_at", "expires", "ttl"} {
		if strings.Contains(block, forbidden) {
			t.Errorf("charger_command_outcomes must not expire, found %q", forbidden)
		}
	}
}

func TestP0MigrationContainsRequiredTablesAndIndexes(t *testing.T) {
	schema := readP0Migration(t)
	for _, table := range []string{
		"user_accounts",
		"admin_accounts",
		"stations",
		"chargers",
		"charging_orders",
		"order_events",
		"wallet_accounts",
		"wallet_transactions",
		"operation_logs",
		"idempotency_records",
		"outbox_events",
	} {
		if _, ok := tableBlocks(schema)[table]; !ok {
			t.Errorf("migration does not define %s", table)
		}
	}
	for _, needle := range []string{
		"primary key (scope, idempotency_key)",
		"where published_at is null",
		"jsonb",
	} {
		if !strings.Contains(schema, needle) {
			t.Errorf("migration missing structural requirement %q", needle)
		}
	}
}

func TestP0MigrationUsesContractIDTypes(t *testing.T) {
	schema := readP0Migration(t)
	blocks := tableBlocks(schema)

	// The frozen OpenAPI contract exposes int64 IDs for these aggregates, so
	// their surrogate keys must be BIGINT identity columns.
	for _, table := range []string{
		"user_accounts",
		"admin_accounts",
		"stations",
		"chargers",
		"charging_orders",
		"order_events",
		"wallet_transactions",
		"operation_logs",
		"outbox_events",
	} {
		block, ok := blocks[table]
		if !ok {
			t.Fatalf("migration does not define %s", table)
		}
		if !strings.Contains(block, "id bigint generated by default as identity primary key") {
			t.Errorf("%s must declare id as bigint identity primary key", table)
		}
	}
	if block, ok := blocks["wallet_accounts"]; !ok || !strings.Contains(block, "user_id bigint primary key") {
		t.Errorf("wallet_accounts must declare user_id as bigint primary key")
	}
	if strings.Contains(schema, "id text primary key") {
		t.Errorf("surrogate primary keys must be bigint identity, not text")
	}

	for _, needle := range []string{
		"station_id bigint not null references stations (id)",
		"user_id bigint not null references user_accounts (id)",
		"charger_id bigint not null references chargers (id)",
		"order_id bigint not null references charging_orders (id)",
		"order_id bigint references charging_orders (id)",
	} {
		if !strings.Contains(schema, needle) {
			t.Errorf("migration missing foreign key requirement %q", needle)
		}
	}
}

func TestP0MigrationMatchesFrozenContract(t *testing.T) {
	schema := readP0Migration(t)
	blocks := tableBlocks(schema)

	stations := blocks["stations"]
	for _, needle := range []string{
		"status text not null default 'open' check (status in ('open', 'closed', 'disabled'))",
	} {
		if !strings.Contains(stations, needle) {
			t.Errorf("stations status must match the frozen StationStatus contract: %q", needle)
		}
	}

	chargers := blocks["chargers"]
	for _, needle := range []string{
		"connector_type text not null default 'ac' check (connector_type in ('ac', 'dc'))",
		"power_watt bigint not null default 0 check (power_watt >= 0)",
		"status text not null default 'idle' check (status in ('idle', 'occupied', 'fault', 'restarting', 'disabled'))",
		"unique (id, station_id)",
	} {
		if !strings.Contains(chargers, needle) {
			t.Errorf("chargers columns must match the frozen Charger contract: %q", needle)
		}
	}

	orders := blocks["charging_orders"]
	for _, needle := range []string{
		"status text not null default 'created' check (status in ('created', 'starting', 'charging', 'stopping', 'completed', 'cancelled', 'expired', 'failed'))",
		"order_no text not null unique",
		// An order's station must be the charger's station.
		"foreign key (charger_id, station_id) references chargers (id, station_id)",
	} {
		if !strings.Contains(orders, needle) {
			t.Errorf("charging_orders columns must match the frozen Order contract: %q", needle)
		}
	}

	outbox := blocks["outbox_events"]
	for _, needle := range []string{
		"event_id text not null unique",
		"trace_id text not null default ''",
		"stream text not null default ''",
	} {
		if !strings.Contains(outbox, needle) {
			t.Errorf("outbox_events must carry the approved OutboxRecord fields: %q", needle)
		}
	}

	for _, needle := range []string{
		// One active order per charger, enforced by the database.
		"create unique index if not exists uq_orders_charger_active",
		"where status in ('created', 'starting', 'charging', 'stopping')",
	} {
		if !strings.Contains(schema, needle) {
			t.Errorf("migration missing concurrency constraint %q", needle)
		}
	}
}

// readNumberedMigration returns one numbered migration, lower-cased like the P0 helper.
func readNumberedMigration(t *testing.T, name string) string {
	t.Helper()
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("resolve test filename")
	}
	contents, err := os.ReadFile(filepath.Join(filepath.Dir(filename), "../../../migrations/", name))
	if err != nil {
		t.Fatalf("read migration %s: %v", name, err)
	}
	return strings.ToLower(string(contents))
}

// A-01 persistence: the deletion scheme is only as good as the shape it is stored in, so the shape is
// pinned here. The deletion is an in-place anonymization, which means every field that must change has
// to exist and the invariants that make a half-deleted account impossible have to be declared in the
// migration rather than only in the adapter's comment.
func TestUserProfileMigrationIsComplete(t *testing.T) {
	schema := readNumberedMigration(t, "0008_user_profile_and_deletion.sql")

	for _, needle := range []string{
		"add column if not exists avatar_url text not null default ''",
		"add column if not exists deleted_at timestamptz",
		// invariants: deleted implies disabled, deleted implies no credentials, bounded avatar storage
		"check (deleted_at is null or status = 'disabled')",
		"check (deleted_at is null or password_hash = '')",
		"check (char_length(avatar_url) <= 512)",
		// the read paths all filter on deleted_at, and the partial index only pays for deleted rows
		"create index if not exists idx_user_accounts_deleted_at",
		"where deleted_at is not null",
	} {
		if !strings.Contains(schema, needle) {
			t.Errorf("0008 is missing %q", needle)
		}
	}
	if strings.Contains(schema, "drop column") {
		t.Error("an up migration must not drop anything")
	}

	// The down script has to undo exactly what the up migration added, in an order PostgreSQL accepts
	// (constraints before the columns they reference) and without touching other migrations.
	down := readNumberedMigration(t, "down/0008_user_profile_and_deletion.down.sql")
	for _, needle := range []string{
		"drop constraint if exists user_accounts_avatar_url_length",
		"drop constraint if exists user_accounts_deleted_has_no_credentials",
		"drop constraint if exists user_accounts_deleted_is_disabled",
		"drop index if exists idx_user_accounts_deleted_at",
		"drop column if exists deleted_at",
		"drop column if exists avatar_url",
	} {
		if !strings.Contains(down, needle) {
			t.Errorf("the down script is missing %q", needle)
		}
	}
	// The down script must not be reachable from the embedded set: it is applied by hand only.
	if strings.Contains(schema, "0008_user_profile_and_deletion.down") {
		t.Error("the up migration must not reference the down script")
	}
}
