-- P0 schema for the H5/Go migration baseline.
-- Surrogate primary keys are BIGINT identity columns to match the int64 IDs
-- of the frozen OpenAPI contract; business identifiers stay TEXT.
-- Amounts use integer cents, energy integer watt-hours, time UTC TIMESTAMPTZ.
-- Cross-aggregate consistency (charger/station pairing, one active order per
-- charger) is enforced by database constraints, not application code.

CREATE TABLE IF NOT EXISTS user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT UNIQUE,
    email TEXT UNIQUE,
    display_name TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (phone IS NOT NULL OR email IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS admin_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'OPERATOR' CHECK (role IN ('SUPER_ADMIN', 'OPERATOR', 'AUDITOR')),
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    address TEXT NOT NULL DEFAULT '',
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED', 'DISABLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE TABLE IF NOT EXISTS chargers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id BIGINT NOT NULL REFERENCES stations (id),
    code TEXT NOT NULL,
    connector_type TEXT NOT NULL DEFAULT 'AC' CHECK (connector_type IN ('AC', 'DC')),
    power_watt BIGINT NOT NULL DEFAULT 0 CHECK (power_watt >= 0),
    status TEXT NOT NULL DEFAULT 'IDLE' CHECK (status IN ('IDLE', 'OCCUPIED', 'FAULT', 'RESTARTING', 'DISABLED')),
    price_per_kwh_cents INTEGER NOT NULL DEFAULT 0 CHECK (price_per_kwh_cents >= 0),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (station_id, code),
    -- Referenced by the charging_orders composite FK: an order's station_id
    -- must equal the station of its charger.
    UNIQUE (id, station_id)
);

CREATE TABLE IF NOT EXISTS charging_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no TEXT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES user_accounts (id),
    station_id BIGINT NOT NULL REFERENCES stations (id),
    charger_id BIGINT NOT NULL REFERENCES chargers (id),
    status TEXT NOT NULL DEFAULT 'CREATED' CHECK (status IN ('CREATED', 'STARTING', 'CHARGING', 'STOPPING', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'FAILED')),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    stopped_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    energy_wh BIGINT NOT NULL DEFAULT 0 CHECK (energy_wh >= 0),
    amount_cents BIGINT NOT NULL DEFAULT 0 CHECK (amount_cents >= 0),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- The order's station must be the charger's station.
    FOREIGN KEY (charger_id, station_id) REFERENCES chargers (id, station_id)
);

CREATE TABLE IF NOT EXISTS order_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES charging_orders (id),
    event_id TEXT NOT NULL UNIQUE,
    event_type TEXT NOT NULL,
    from_status TEXT,
    to_status TEXT,
    payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallet_accounts (
    user_id BIGINT PRIMARY KEY REFERENCES user_accounts (id),
    balance_cents BIGINT NOT NULL DEFAULT 0 CHECK (balance_cents >= 0),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_accounts (id),
    order_id BIGINT REFERENCES charging_orders (id),
    transaction_type TEXT NOT NULL CHECK (transaction_type IN ('TOP_UP', 'CHARGE', 'REFUND', 'ADJUSTMENT')),
    amount_cents BIGINT NOT NULL CHECK (amount_cents <> 0),
    balance_before_cents BIGINT NOT NULL CHECK (balance_before_cents >= 0),
    balance_after_cents BIGINT NOT NULL CHECK (balance_after_cents >= 0),
    idempotency_key TEXT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type TEXT NOT NULL CHECK (actor_type IN ('USER', 'ADMIN', 'SYSTEM')),
    actor_id TEXT,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT,
    request_id TEXT,
    payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS idempotency_records (
    scope TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('IN_PROGRESS', 'SUCCEEDED', 'FAILED')),
    response_code INTEGER,
    response_body JSONB,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (scope, idempotency_key)
);

CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL UNIQUE,
    event_type TEXT NOT NULL,
    aggregate_type TEXT NOT NULL,
    aggregate_id TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    trace_id TEXT NOT NULL DEFAULT '',
    stream TEXT NOT NULL DEFAULT '',
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chargers_station_status ON chargers (station_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_user_created ON charging_orders (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_charger_status ON charging_orders (charger_id, status);
-- At most one active order per charger. PostgreSQL is the final concurrency
-- guard: two simultaneous INSERTs race on this index, not on application locks.
CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_charger_active
ON charging_orders (charger_id)
WHERE status IN ('CREATED', 'STARTING', 'CHARGING', 'STOPPING');
CREATE INDEX IF NOT EXISTS idx_order_events_order_created ON order_events (order_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_user_created ON wallet_transactions (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_operation_logs_resource_created ON operation_logs (resource_type, resource_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_idempotency_expires_at ON idempotency_records (expires_at);
CREATE INDEX IF NOT EXISTS idx_outbox_pending ON outbox_events (next_attempt_at, created_at) WHERE published_at IS NULL;
