-- A-05: order reviews, the station comment wall and order appeals
-- (UC-U-12, UC-U-09). Proposal pending B-02 confirmation.

CREATE TABLE IF NOT EXISTS order_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- One review per order (UC-U-12: 每笔订单仅允许一条评价).
    order_no TEXT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES user_accounts (id),
    station_id BIGINT NOT NULL REFERENCES stations (id),
    stars INT NOT NULL CHECK (stars BETWEEN 1 AND 5),
    comment TEXT NOT NULL CHECK (length(comment) BETWEEN 1 AND 500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_order_reviews_station_created
    ON order_reviews (station_id, created_at DESC);

CREATE TABLE IF NOT EXISTS order_appeals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- One appeal per order (UC-U-09: 相同申诉和重复审核不得重复记账).
    order_no TEXT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES user_accounts (id),
    reason TEXT NOT NULL CHECK (length(reason) BETWEEN 1 AND 500),
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED')),
    decided_by BIGINT REFERENCES admin_accounts (id),
    decided_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_order_appeals_status_created
    ON order_appeals (status, created_at DESC);
